package org.example.springboot.r6api;

public class RequestParam {
    public static final String[] GENERAL_PVP = {
            "generalpvp_timeplayed",
            "generalpvp_matchplayed",
            "generalpvp_killassists",
            "generalpvp_revive",
            "generalpvp_headshot",
            "generalpvp_penetrationkills",
            "generalpvp_meleekills",
            "generalpvp_matchwon",
            "generalpvp_matchlost",
            "generalpvp_kills",
            "generalpvp_death",
            "generalpvp_bullethit",
            "generalpvp_bulletfired"
    };

    public static final String[] OPERATORS = {
            "operatorpvp_timeplayed",
            "operatorpvp_roundwon",
            "operatorpvp_roundlost",
            "operatorpvp_kills",
            "operatorpvp_death",
            "operatorpvp_headshot",
            "operatorpvp_meleekills",
            "operatorpvp_totalxp",
            "operatorpvp_smoke_poisongaskill",
            "operatorpvp_mute_gadgetjammed",
            "operatorpvp_sledge_hammerhole",
            "operatorpvp_thatcher_gadgetdestroywithemp",
            "operatorpvp_castle_kevlarbarricadedeployed",
            "operatorpvp_ash_bonfirewallbreached",
            "operatorpvp_pulse_heartbeatspot",
            "operatorpvp_thermite_reinforcementbreached",
            "operatorpvp_doc_teammaterevive",
            "operatorpvp_rook_armortakenteammate",
            "operatorpvp_twitch_gadgetdestroybyshockdrone",
            "operatorpvp_montagne_shieldblockdamage",
            "operatorpvp_glaz_sniperkill",
            "operatorpvp_fuze_clusterchargekill",
            "operatorpvp_kapkan_boobytrapkill",
            "operatorpvp_tachanka_turretkill",
            "operatorpvp_blitz_flashedenemy",
            "operatorpvp_iq_gadgetspotbyef",
            "operatorpvp_jager_gadgetdestroybycatcher",
            "operatorpvp_bandit_batterykill",
            "operatorpvp_buck_kill",
            "operatorpvp_frost_dbno",
            "operatorpvp_blackbeard_gunshieldblockdamage",
            "operatorpvp_valkyrie_camdeployed",
            "operatorpvp_capitao_lethaldartkills",
            "operatorpvp_hibana_detonate_projectile",
            "operatorpvp_echo_enemy_sonicburst_affected",
            "operatorpvp_cazador_assist_kill",
            "operatorpvp_black_mirror_gadget_deployed",
            "operatorpvp_dazzler_gadget_detonate",
            "operatorpvp_caltrop_enemy_affected",
            "operatorpvp_concussionmine_detonate",
            "operatorpvp_concussiongrenade_detonate",
            "operatorpvp_phoneshacked",
            "operatorpvp_attackerdrone_diminishedrealitymode",
            "operatorpvp_tagger_tagdevice_spot",
            "operatorpvp_rush_adrenalinerush",
            "operatorpvp_barrage_killswithturret",
            "operatorpvp_deceiver_revealedattackers",
            "operatorpvp_maverick_wallbreached",
            "operatorpvp_clash_sloweddown",
            "operatorpvp_nomad_airjabdetonate",
            "operatorpvp_kaid_electroclawelectrify",
            "operatorpvp_mozzie_droneshacked",
            "operatorpvp_gridlock_traxdeployed",
            "operatorpvp_nokk_observationtooldeceived",
            "operatorpvp_warden_killswithglasses",
            "operatorpvp_goyo_volcandetonate",
            "operatorpvp_amaru_distancereeled",
            "operatorpvp_kali_gadgetdestroywithexplosivelance",
            "operatorpvp_wamai_gadgetdestroybymagnet",
            "operatorpvp_oryx_killsafterdash",
            "operatorpvp_iana_killsafterreplicator",
            "operatorpvp_caveira_interrogations",
    };

}

